# -*- coding: utf-8 -*-
"""translator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZbs7sYY3F2H3dxo_vh71OzG2gTzRU5Q
"""

pip install translate

from translate import Translator

Text = 'this is colab,how are you all? hope everyone are doing good'
translator = Translator(from_lang="English",to_lang="Hindi")
translation = translator.translate(Text)
print('translated text:  ', translation)

